# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # set up the Docker Buildx plugin, which enables the workflow to build and push multi-platform Docker images.
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # docker/login-action is the Action provided by Docker for logging into container registries.
      - name: Log in to GitHub container registry
        uses: docker/login-action@v1.10.0
        with:
          # GitHub Container Registry (ghcr.io), GitHub's own container registry service.
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          # Docker Hub's registry (docker.io)
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # In Bash, the syntax ${variable,,} converts all characters in the specified variable to lowercase.
      # GITHUB_REPOSITORY is an environment variable provided by GitHub, containing the full name of the repository (e.g., username/repository)
      # Docker image names must be lowercase.
      - name: Lowercase the repo name and username
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ env.REPO }}:${{ github.sha }}
          file: ./Dockerfile
